services:
  db-main:
    image: postgres:14
    restart: always
    ports:
      - 5431:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      - cat_show_db:/var/lib/postgresql/data


volumes:
  cat_show_db: